[custom]
;设置规则标志位
#ruleset=REJECT,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/apm.list
#阻断加速，提升优先级，因为这些站点（包括CDN下载）实在是太慢了
ruleset=Proxies,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/boost.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
#ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
#ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
#ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
#ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
#ruleset=REJECT,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Privacy.list
#ruleset=REJECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Hijacking/Hijacking.list
#ruleset=REJECT,https://limbopro.com/Adblock4limbo.list 
#ruleset=REJECT,https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt
#屏蔽App广告，适合路由器使用的规则（手机全局挂的只有quanx，这个没什么用，所以注释）
#ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
#ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
#ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
#ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
#ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
#两个下载防止误跑流量
ruleset=DIRECT,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/DownloadPatch.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
#steam下载服务器
ruleset=DIRECT,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/steamdownload.list
#视频网站不用跑太多流量
#ruleset=DIRECT,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/video.list
###############下载加速 虽然但是 流量跑太多了
#ruleset=Proxies,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/2X.list
#游戏平台加速
ruleset=Proxies,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/gameplatform.list
#微软全部加速，微软经常被阻断
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list
#DMM玩手游对IP有特别要求
ruleset=DMM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/DMM/DMM.list
#仅日本IP可用
ruleset=Japan,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/DmmDLFz.list

#不允许日本IP 省事直接扔HK节点
ruleset=Hongkong,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/notJP.list
#ruleset=Bilibili,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/BL.list

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list

#Apple直连
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
#Spotify ip变动会需要重新登录
#ruleset=Spotify,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/spotify.list

ruleset=DIRECT,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/windowsoft.list
ruleset=DIRECT,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/kaspersky.list
ruleset=DIRECT,https://raw.githubusercontent.com/Ghou133/Ghou133.github.io/master/archives/UnBanPatch.list

ruleset=Proxies,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=Others,[]FINAL
#ruleset=Proxies,[]FINAL

#custom_proxy_group=Proxies`select`[]HKFast`[]Free`[]Fallback`.*
#考虑到free的节点不应该放进选择
custom_proxy_group=Proxies`select`[]Auto`[]Free`.*
#custom_proxy_group=Proxies`select`[]Auto`[]Free`(Hong Kong|Japan|Taiwan|Singapore|United States|Germany|United Kingdom|South Korea|France|Netherlands|India|Türkiye)`
custom_proxy_group=Bilibili`select`[]DIRECT`[]Hongkong`[]Taiwan
custom_proxy_group=Spotify`select`[]Japan`[]Hongkong`[]Taiwan`[]Singapore`[]United States`[]DIRECT
#custom_proxy_group=DownloadBoots`select`[]DIRECT`[]Proxies
#custom_proxy_group=Ehentai`select`[]Proxies`[]Free`[]DIRECT`.*
#custom_proxy_group=Microsoft|Onedrive`select`[]DIRECT`[]Proxies`[]REJECT
#custom_proxy_group=Steam`select`[]DIRECT`[]Proxies
custom_proxy_group=DMM`select`[]Japan`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]Tokyo|JP|Japan)
;custom_proxy_group=🇭🇰`url-test`(港|HK|Hong Kong)
;custom_proxy_group=🇹🇼`url-test`(广台|新北|彰化|TW|Taiwan|湾)
#custom_proxy_group=Fast`url-test`.*`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=Japan`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]Tokyo|JP|Japan)`http://www.gstatic.com/generate_204`1800
custom_proxy_group=Hongkong`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`1800
custom_proxy_group=Taiwan`url-test`(台湾|TW|Taiwan)`http://www.gstatic.com/generate_204`1800
custom_proxy_group=Singapore`url-test`(新加坡|Sg|Singapore)`http://www.gstatic.com/generate_204`1800
custom_proxy_group=United States`url-test`(US|美国|United States)`http://www.gstatic.com/generate_204`1800
custom_proxy_group=Free`url-test`(免费|试用|free|自由|公益)`http://www.gstatic.com/generate_204`120
custom_proxy_group=Auto`fallback`[]Hongkong`[]Japan`[]Taiwan`[]Singapore`[]United States`[]Free`http://www.gstatic.com/generate_204`180
custom_proxy_group=Others`select`[]Proxies`[]DIRECT
enable_rule_generator=true
overwrite_original_rules=true
